### Get all todos
GET http://localhost:8080/v2 HTTP/1.1

### Get single todos
GET http://localhost:8080/v2/4 HTTP/1.1

### add todo
POST  http://localhost:8080/v2 HTTP/1.1
Content-Type: application/json

{
    "name": "test 1",
    "description": "testtttt",
    "groos_amount": "100"

}
### delete todo

DELETE  http://localhost:8080/v2/2 HTTP/1.1

### update todo
PUT  http://localhost:8080/v2/3 HTTP/1.1
Content-Type: application/json

{
    "name": "Updated test 1",
    "description": "testtttttt",
    "groos_amount": "100"

}
